### ISSUE TITLE
Cannot "pin" the counter to my game window.

### ISSUE THREAD

**Issue by UO282497** [ssjshields/archetype-counter#14]
I'm not able to have the game open (and on focus), and the counter on the same screen. I have also tried to move it to my second monitor but I cannot do it too.

**Comment by ssjshields** [comment]
hi @UO282497 thanks for contacting us regarding this report.
could you confirm:
- how many monitors you have, and their order (in display settings, e.g. 2, 1 or 1, 2)
- is pokeMMO in windowed or full-screen

if you go into a battle, if turned on, does the Counter go into BUSY mode?

also, if  possible, it would much easier to reach out via discord as we could communicate faster and resolve this issue quickly.

https://discord.gg/rYg7ntqQRY

**Comment by ssjshields** [comment]
will reopen if issue occurs again
