### ISSUE TITLE
Swablu failed scan

### ISSUE THREAD

**Issue by Drunkaa** [ssjshields/archetype-counter#15]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/139825495/79a0e6eb-66da-4191-b14b-e2291340cf24)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/139825495/1bfecb8c-dc04-4300-b9a1-75a4b5baf294)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/139825495/8424d8df-ae9b-4f62-a280-7068d8166371)
###################################
#   ARCHETYPE COUNTER OCR DEBUG   #
###################################

-------------------
| Before Cleanup: |
-------------------

Swabiu Lv. 31

------------------
| After Cleanup: |
------------------

Swabiu

----------------
| Horde Count: |
----------------

0

----------------------
| Pixel Color Check: |
----------------------

fffb00fb

################################
#   END OF COUNTER OCR DEBUG   #
################################

**Comment by ssjshields** [comment]
@Drunkaa thank you for this report. it will be fixed in the next patch.
