### ISSUE TITLE
Farfetch'd encounter adding to count but continuously displaying error message

### ISSUE THREAD

**Issue by JBCastr** [ssjshields/archetype-counter#20]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12514566/DEBUG_OCR_OUTPUT.txt)

![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/144038525/74729f8d-5d6a-4960-95b4-8bafa1d3fed3)

![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/144038525/149e1efa-2a5b-457b-9ee7-fdb8a1c0ecf8)

![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/144038525/174aa9a5-b017-4fc2-a171-8f06dd740751)

**Comment by ssjshields** [comment]
@JBCastr Hey there, this bug should of been fixed a few updates ago. Could you ensure you're on the latest main build and try encountering Farfetch'd again?

**Comment by ssjshields** [comment]
@AnonymousPoke added additional logic when processing monster that have special glyphs or spaces in their names, as well as added Farfetch'd to the name fix list. As of recent updates this list is now available for the user to modify or add-on to, if there is every a consistent failed to scan issue (occurs more often with less supported languages.) you can add the monsters name to the file to correct the scan.

**Comment by JBCastr** [comment]
> > That screenshot was actually from the update I downloaded today. I DID just directly copy the counter config files folder from the previous version and pasted it into the newer version. Maybe that caused issues? I'll go ahead and download a completely fresh version without tampering with it to see if it works.
> 
> If the CounterConfig_PokemonNameFix file was overwrote, that could be why this is occuring. Ensure you have the latest copy of that file, you can still use your old hunt profile files.

This is exactly what happened. My bad, it was a user error. Thanks for the help though!
