### ISSUE TITLE
Failed Scan - Trainer username

### ISSUE THREAD

**Issue by ShaqOT** [ssjshields/archetype-counter#21]
New to this, i hope this helps, loving the counter so will do my best to support. 
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/141530892/62ba199b-ce9f-4a88-a015-d7582f97bce2)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/141530892/22eeb250-e397-4862-8559-6e512c754d8c)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/141530892/3f831a18-f383-4ce6-8149-8e3818123601)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12515092/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
@ShaqOT, please download the latest main build and see if this issue occurs again.
