### ISSUE TITLE
Single encounter Ponyta failed scan

### ISSUE THREAD

**Issue by Veverlyy** [ssjshields/archetype-counter#25]
Pokemmo client is fullscreen.

![image](https://github.com/ssjshields/archetype-counter/assets/128685689/e5bc711b-575c-4cb6-9500-e456b701a137)

**Comment by ssjshields** [comment]
@Veverlyy 
The Counter has never been able to support fullscreen. As of several months ago we implemented a message that alerts you that you cannot use the Counter in fullscreen, inturn removing mentioning this from the readme.

So, first ensure you have the latest version of the Counter. Second enable borderless fullscreen instead, and refer to https://github.com/ssjshields/archetype-counter/issues/16. Finally, as stated in the screenshot you uploaded- please provide the debug log which should be opened in Explorer when you click the "button that says report ". We cannot do anything without the debug logs.

**Comment by Veverlyy** [comment]
Nvm now it's working properly, I just had to set borderless window

**Comment by Veverlyy** [comment]
Nvm now it's working properly, I just had to set borderless window.
Thanks

**Comment by ssjshields** [comment]
On the latest build, it should still alert you that you are using fullscreen mode and that you can't continue.

**Comment by AnonymousPoke** [comment]
> On the latest build, it should still alert you that you are using fullscreen mode and that you can't continue.

It definitely does do this. I would need confirmation from the user that this for some reason does not work. At this point, the issue can be closed.
