### ISSUE TITLE
Failed scan - beta build Traditional Chinese

### ISSUE THREAD

**Issue by Secrettw** [ssjshields/archetype-counter#29]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/114652583/a7bffd02-67af-4d9b-8c18-998754231232)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12708008/DEBUG_OCR_OUTPUT.txt)

![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/114652583/5f967f0c-5bb4-406f-9ca8-e2f6c5ebfcfd)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12708016/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
Hello @Secrettw, please download the latest "main" build again as this has been recently updated with better OCR support and should overall have a better experience. 

*You still may encounter some Pokemon names scanned incorrectly by the new Tesseract OCR that counter uses, but please use the NameFix file to manually clean up and names you run into.
