### ISSUE TITLE
Failed Scan - Gloom Bug

### ISSUE THREAD

**Issue by Ethan94ESP** [ssjshields/archetype-counter#30]
When Gloom appears as single encounter it show me up that screen error msg attached.
![image](https://github.com/ssjshields/archetype-counter/assets/30560668/dba6d9ee-9730-49c1-a64c-012da0daaf47)

**Comment by ssjshields** [comment]
Hey @Ethan94ESP. Can you confirm which branch you are using?
If you are using the main branch, please download the latest Beta.

Can you also upload the log generated by the failed scan?
I am assuming it is due to the "Sleep" status icon, but without the log it is hard to tell.

**Comment by Ethan94ESP** [comment]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12777649/DEBUG_OCR_OUTPUT.txt)
Using main chainging to Beta ty.

**Comment by ssjshields** [comment]
> [DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12777649/DEBUG_OCR_OUTPUT.txt) Using main changing to Beta ty.

Yeah- looks like the "Z - Sleeping" status icon. Hopefully using Beta resolves, but if this persists, let us know.

**Comment by Ethan94ESP** [comment]
Using beta it happens too :(

**Comment by Ethan94ESP** [comment]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12777663/DEBUG_OCR_OUTPUT.txt)

**Comment by ssjshields** [comment]
> Using beta it happens too :(

Open the `CounterConfig_PokemonNameFix.txt` file.
Add the entry on a new line: `aGloom ; Gloom`

**Comment by Ethan94ESP** [comment]
![image](https://github.com/ssjshields/archetype-counter/assets/30560668/3abf3c0e-4d36-4d7e-a285-4d8d81021396)

**Comment by ssjshields** [comment]
Check the Counters Chinese mode setting please. It may have been left on during a commit.

**Comment by Ethan94ESP** [comment]
![image](https://github.com/ssjshields/archetype-counter/assets/30560668/28f2c46f-41ad-4c44-8748-86ba680a65be)
its there how can i remove it?

**Comment by ssjshields** [comment]
> ![image](https://user-images.githubusercontent.com/30560668/271842221-28f2c46f-41ad-4c44-8748-86ba680a65be.png) its there how can i remove it?

For now- revert to Main. Use the same [name fix](https://github.com/ssjshields/archetype-counter/issues/30#issuecomment-1742136558) though.

**Comment by Ethan94ESP** [comment]
let me try thanks :D

**Comment by ssjshields** [comment]
> let me try thanks :D

Make sure it is `failedscan; correct name`
my original post had an extra space. my apologies

**Comment by Ethan94ESP** [comment]
![image](https://github.com/ssjshields/archetype-counter/assets/30560668/ef31ce67-e85d-40fb-919c-9e2937cf7c05)
its fine now?

**Comment by ssjshields** [comment]
> ![image](https://user-images.githubusercontent.com/30560668/271842630-ef31ce67-e85d-40fb-919c-9e2937cf7c05.png) its fine now?

This should resolve. Keep an eye out for similar issues- they can be fixed this way.
Still, feel free to report any instances you find.

**Comment by Ethan94ESP** [comment]
Nice glad to help thanks for the support :D

**Comment by ssjshields** [comment]
> Nice glad to help thanks for the support :D

Anytime, if it doesn't fix, let us know- it could be related to when the results and cleaned.

**Comment by Ethan94ESP** [comment]
Working fine u can close the issue!
