### ISSUE TITLE
Unable to scan Pokemon - Counter still works

### ISSUE THREAD

**Issue by user9979** [ssjshields/archetype-counter#31]
Hi, basically the general counter always works, but with certain pokemon it gives me the "Unable to scan Pokemon" error and that certain species counter wont go up.
Worked perfectly until one hour ago, nothing changed in the meantime, and i have the latest version.

I get the error with Miltank, ditto, drowzee, jigglypuff, psyduck, ekans, mareep, flaaffy
Works perfectly with Rattata, tentacool

![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/146668488/658bdd08-f678-4263-8a04-2ea07597956c)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/146668488/97b998d3-a9a2-4f4d-bd1f-ff8f20032acb)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/146668488/b673717e-b31a-493c-a875-90eefdc2ac00)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12778024/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
Hello @user9979, Please download the latest "main" build again as this has been recently updated with better OCR support and should overall have a better experience.
