### ISSUE TITLE
lavender tower x3 gastly horde not counting properly

### ISSUE THREAD

**Issue by BrokenTed** [ssjshields/archetype-counter#33]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/130982810/1de8d51d-7758-4edc-afa8-d559cb191f7d)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/130982810/c7f0dacc-af42-475b-b77b-fae33d8ac5b7)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/130982810/967b9ee5-2301-4960-80ed-b2818f89fdfd)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12807589/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
@BrokenTed, thank you for providing the error report. From the looks of it, you are on a slightly later build. Please re-download the latest build to have more reliable OCR scanning on the Pokémon names.

**Comment by BrokenTed** [comment]
tyty
