### ISSUE TITLE
Failed Scans - after pokemon learn new skill/evolve after counter update

### ISSUE THREAD

**Issue by ofir-mev** [ssjshields/archetype-counter#34]
still happening after update here the new bug report maybe it will help you.
 
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/57320827/68404410-b38e-42d5-acb8-0cb1312a059d)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12884392/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/57320827/d1c01ee6-0ef2-4402-baca-caef028b4145)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/57320827/8188d2ff-f7e3-4624-ba7d-e1aaa8a45f1d)

**Comment by smallerYeet** [comment]
same here
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/68237474/1d968890-7e60-4a92-bf05-17255e254d42)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/68237474/12098403-414b-4eee-93f4-2050dd008c1a)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/68237474/60703311-b5ca-4cb3-a699-0f3fe096ad8b)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13539205/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
There must be a particular color in the top left corner where the counter thinks it is in battle (Which is how we detect). Please try the new version 4.0.0.1 to see if it resolves the issue.
