### ISSUE TITLE
Failed Scan

### ISSUE THREAD

**Issue by aptxelo** [ssjshields/archetype-counter#35]
<img width="1280" alt="ArchetypeScreenshot" src="https://github.com/ssjshields/archetype-counter/assets/148380799/19a7e227-3cde-4c4e-b79b-7e4d98858684">
<img width="891" alt="ArchetypeScreenshotEncounter" src="https://github.com/ssjshields/archetype-counter/assets/148380799/7cebab52-ea04-4b89-a730-8ccd1d6f9591">
<img width="891" alt="ArchetypeScreenshotMagick" src="https://github.com/ssjshields/archetype-counter/assets/148380799/115b0d30-b3fc-4a0f-8ae5-6dbbad9977ca">
<img width="1280" alt="ArchetypeScreenshotSetPixel" src="https://github.com/ssjshields/archetype-counter/assets/148380799/2e198d90-35da-4c3a-bfd2-dbce59a9b2e0">
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13032138/DEBUG_OCR_OUTPUT.txt)
I wonder if there is any way I can solve this problem.

**Comment by AshHash** [comment]
I've been getting failed scans as well. It seems to only pop up when the encountered wild pokemon is asleep and I'm using the archetype theme. ![image](https://github.com/ssjshields/archetype-counter/assets/9087395/86aa3e2e-0785-4b31-82d2-816ee0d57c6b)

**Comment by mkfc13** [comment]
same issue with me, failed scans happens when wild pokemon is asleep.

**Comment by Aliviessa** [comment]
This happened to me as well. Check out this post for an easy fix: https://github.com/ssjshields/archetype-counter/issues/24#issuecomment-1711774320

**Comment by AnonymousPoke** [comment]
All, please download latest main branch build to resolve your issues.
