### ISSUE TITLE
Failed Scan while typing

### ISSUE THREAD

**Issue by ObiWanKebabi** [ssjshields/archetype-counter#36]
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/150699988/815ae200-dec3-42b9-9a64-b97832815dd5)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/150699988/b9d405ea-dd0f-4cfc-87ee-a30891a74cb7)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13336160/DEBUG_OCR_OUTPUT.txt)

**Comment by ObiWanKebabi** [comment]
![image](https://github.com/ssjshields/archetype-counter/assets/150699988/39cef2f0-bbb7-4b88-9c4e-22ac3071eb91)

**Comment by ssjshields** [comment]
![image](https://github.com/ssjshields/archetype-counter/assets/88489119/8c0f42c9-360a-4fca-be0e-f286581dcb57)

Town location / charm status bled over into the monster name, unrelated to typing.

Only way to resolve is to expand the PokeMMO window, or edit that specific text string.
