### ISSUE TITLE
Failed Scan if Pokemon sleeping

### ISSUE THREAD

**Issue by DreVla** [ssjshields/archetype-counter#37]
```
###################################
#   ARCHETYPE COUNTER OCR DEBUG   #
###################################

-------------------
| Before Cleanup: |
-------------------

H Gloom Lv. 29

------------------
| After Cleanup: |
------------------

HGloom

----------------
| Horde Count: |
----------------

0

----------------------
| Pixel Color Check: |
----------------------

Auto

-----------------
| Picture Mode: |
-----------------

PrintWindow (Default)

-----------------
| OCR Language: |
-----------------

English

################################
#   END OF COUNTER OCR DEBUG   #
################################
```

![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/32488956/c68a4816-48b9-4b1e-b0a8-b9aa3ca16f15)

![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/32488956/32b9354c-9945-4606-8b49-ef1e6db20c50)

![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/32488956/c23255af-fba3-4111-8065-88097ab2ef58)

**Comment by AnonymousPoke** [comment]
@DreVla - Please download latest main branch build as we believe we have resolved the sleep icon issue.
