### ISSUE TITLE
Unable to scan Pokemon due to custom strings

### ISSUE THREAD

**Issue by wudengshenye** [ssjshields/archetype-counter#38]
![WK4U0YENXBO_EEJ}@@OJ_`M](https://github.com/ssjshields/archetype-counter/assets/49291824/e75f9f86-4614-43b9-9399-079906d599d2)

**Comment by ssjshields** [comment]
@wudengshenye can you upload your error logs? Thank you

**Comment by AnonymousPoke** [comment]
@wudengshenye It seems you might have a mod that puts the Pokémon type in front of the name. AC does not currently support this. Please remove and the issue should go away.
