### ISSUE TITLE
Endless Failed Scans

### ISSUE THREAD

**Issue by BabyFaceSimpsun** [ssjshields/archetype-counter#39]
I thought it was an issue with my themes, but I've bounced back and forth to the default theme several times and had the same issue. It's non-stop, it'll count the encounter as 2, sometimes 3 then give this message. Sometimes starting and stopping the counter a few times gets it to chill out but it's far past being worth it at this point. Sometimes it'll work for awhile, then start back up if I tabbed out and won't seem to fix. Hoping someone can fix this, I like the counter but the errors have pissed me off lmao. 
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13626427/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/153409687/2146ac89-5b0c-49b0-9115-5b8638278795)

**Comment by BabyFaceSimpsun** [comment]
Strange as it is, I think I figured it out and it's only a few minutes later lmao. The counter bugs when you have Nvidia Instant Replay on. Which, I do want to report that bug. But it's nice to have found to source, even if it is a bit embarrassing to have posted in anger then find the issue a few minutes later haha. Not sure if it's the Icon for the overlay of Nvidia or what, but if it's running and you tab out of PokeMMO, the counter will fail. If it's closed, no issues, even with my weirdest themes. Do with that info what you will lmao.

**Comment by BabyFaceSimpsun** [comment]
I thought I found the problem and closed this, I did not lmao.

**Comment by ssjshields** [comment]
Well, first of all it is for sure your theme causing the error in this picture.

We can't address errors if you don't send us the logs. Instead of getting "pissed off" at them, how about forwarding them?

**Comment by BabyFaceSimpsun** [comment]
I thought it might be, but switching to the default theme doesn't stop it. The only solution seems to be restarting both PokeMMO and the counter several times in a row until the stars align, like they are right now. And please don't take offense, I meant nothing by it. Pissed off is a common phrase for me. I love your counter. 

I thought I did post logs, it said to post the text file from the debug menu, is that not what the DEBUG_OCR file is that I posted?

**Comment by AnonymousPoke** [comment]
@BabyFaceSimpsun Please download latest main branch build and this should resolve your issues.
