### ISSUE TITLE
Infinite Failed scans

### ISSUE THREAD

**Issue by RyuzakiOsu** [ssjshields/archetype-counter#40]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/153439216/b9aee988-4f40-4fd1-9058-7acea3cb1cea)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/153439216/033eedd8-2b20-43e6-b098-4fc827bedb4c)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/153439216/7e2808e3-dced-4f58-bf65-dfc68157f6e2)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13629183/DEBUG_OCR_OUTPUT.txt)

**Comment by RyuzakiOsu** [comment]
so i don't know what happened, i just clicked on the screenshots on the folder and it fixed itself

**Comment by RyuzakiOsu** [comment]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13629251/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/153439216/85e15bd9-b4e7-4239-b3e6-55f6b330fdac)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/153439216/ff9cee84-c5ec-48d8-bd56-dfb40d268400)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/153439216/ba6f7404-3a0f-4af2-a734-a753591dd9b1)

**Comment by AnonymousPoke** [comment]
@RyuzakiOsu Please download latest main branch build as this should resolve your issues.

**Comment by AnonymousPoke** [comment]
Issue confirmed resolved.
