### ISSUE TITLE
Infinite failed scans, only on magnemite hordes

### ISSUE THREAD

**Issue by Jkatz5490** [ssjshields/archetype-counter#41]
I was hunting magnemites before, and it was working for about the first 1,500 scans. then all the sudden the scanning stopped working each time i try to scan. the overall total counter was still working, but the count for the magnemite pokemon individually had completely stopped and i am getting a failed scan every time. i tried uninstalling, reinstalling, closing pokemmo and reopening, and closing the counter and reopening and resetting my theme to default, none of that fixed it. 
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/103266077/9428b8a8-ac7b-42e9-896a-1e6faceafb22)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/103266077/2a533ec1-d726-4ccb-813f-cbf54ba49832)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/103266077/ad57b800-948b-4055-9159-2b0cad470dbc)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13664049/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
@Jkatz5490 Please download latest main branch build as it should resolve your issues you are experiencing.

**Comment by AnonymousPoke** [comment]
Issue confirmed resolved.
