### ISSUE TITLE
endless failed scans

### ISSUE THREAD

**Issue by RyuzakiOsu** [ssjshields/archetype-counter#42]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13796449/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/153439216/dd27cb02-3d8d-4911-96a1-9a41b5aaa20c)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/153439216/abfeacad-9d6a-4ee1-b001-c98e04aecf0d)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/153439216/a8cd0ede-22c4-46ec-88ab-ac98a2c56a4c)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/153439216/8a0afe84-1013-4954-b914-8cd67db7c885)

**Comment by ssjshields** [comment]
This issue has been fixed several revisions ago. please update the latest counter version before submitting a bug report.
