### ISSUE TITLE
Failed scan for Krabby alone

### ISSUE THREAD

**Issue by ChaosQ8** [ssjshields/archetype-counter#43]
So im hunting zapdos in route 10 kanto, and have the archetype counter mod on to track my encounters.

Been getting the failed to scan for Krabby alone and no other pokemons were giving me that issue and im not sure why exactly its happening to me honestly
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/155388848/89def762-9a47-4413-8c5f-fea42905d712)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/155388848/e4c10975-f0fd-4f63-ab17-796d4b987652)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/155388848/94ae245f-5dc9-4df2-b86f-d7f37c0f3978)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/155388848/7467292f-ae19-4786-b5f0-a150b9fb672c)
![ArchetypeScreenshotSetPixel](https://github.com/ssjshields/archetype-counter/assets/155388848/9064bfca-0fe1-4d58-9e78-6ce46cb08a4c)

and this is the text output for the failed scan if needed as well 
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13805627/DEBUG_OCR_OUTPUT.txt)

Thank you for reading this and sorry if its a known issue but im confused how to solve the issue, and i hope i didnt take too much from your time

**Comment by realmadrid1809** [comment]
Huh the text doesn't match what's on the screen whatsoever. Was this a one time thing or does it happen repeatedly? If it's the latter then does it happen everytime you encounter a krabby? Any other routes or only this specific spot?

**Comment by ChaosQ8** [comment]
@realmadrid1809 

I just fixed the issue by going to the name change fix and added both names in before/after cleanup process and then used the after cleanup name to Krabby and thankfully im not getting the error message again and its counting towards the encounter ^-^

**Comment by AnonymousPoke** [comment]
Issue resolved in v4.0.0.1.
