### ISSUE TITLE
Unable to scan Gloom, Bellsprout and Weepinbell

### ISSUE THREAD

**Issue by Romsmesme** [ssjshields/archetype-counter#44]
Hello, I've been using your encounter counter for a few weeks now, and I'm regularly having issues with counting Gloom (single encounter, no issue with hordes), Bellsprout and Weepinbell (both with single enc, I don't know about hordes).

Here is an example with Bellsprout
![1](https://github.com/ssjshields/archetype-counter/assets/118564463/8f9a2502-fe8c-41e3-8c31-2fbac29986ab)

[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13819034/DEBUG_OCR_OUTPUT.txt)

I tried changing the Picture mode setting, tried resizing the Battle window size (as I set mine smaller than the default setting).
Haven't tried the Name Fix thing, as I couldn't find the file, only the .png file.

Thanks for your time, and if you need Gloom and Weepinbell pictures and debug files, tell me!

EDIT: I have no other mods, no custom theme, only strings

**Comment by realmadrid1809** [comment]
Ok, switch back to the default picture method, find another failed encounter and send us ALL the debug files (text file + 4 pngs). That way we can see what went wrong.

**Comment by Romsmesme** [comment]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/118564463/0172ed69-db3b-43d7-a370-74c7963402be)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/118564463/fac38778-ce0e-41f0-8e2f-6888bbd7fab1)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/118564463/95537df0-4522-4dd1-8f8c-2cd48fcff74c)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/118564463/85c6e45e-7001-4aed-a0e3-36af98848f51)

[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13820863/DEBUG_OCR_OUTPUT.txt)

**Comment by Romsmesme** [comment]
Okay it seems to have fixed it, which is weird as I'm sure I tested going back to 100% battle window size and there was still issues

Thank you anyways !

**Comment by AnonymousPoke** [comment]
Issued resolved in v4.0.0.1.
