### ISSUE TITLE
Unable to scan male Nidoran

### ISSUE THREAD

**Issue by Lleywinn** [ssjshields/archetype-counter#46]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/13855158/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/155923470/85457fcf-2a6b-420b-85ab-bbece4f9e4fb)

**Comment by AnonymousPoke** [comment]
Issue resolved in v4.0.0.1.
