### ISSUE TITLE
Can't open the .lnk with custom file explorer (?)

### ISSUE THREAD

**Issue by ZzPSYCHOzZ** [ssjshields/archetype-counter#47]
It does nothing then I try to open, but I can open the .bat one tho

**Comment by ssjshields** [comment]
@ZzPSYCHOzZ Is the Counter extracted into the proper directory? **PokeMMO/mods**

**Comment by ZzPSYCHOzZ** [comment]
Yes
![imagem_2024-01-26_180848957](https://github.com/ssjshields/archetype-counter/assets/57847604/25a74ae7-b788-4d93-8bfc-7546a9dca3bb)
