### ISSUE TITLE
Unable to scan golduck

### ISSUE THREAD

**Issue by RyuzakiOsu** [ssjshields/archetype-counter#48]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14232925/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/153439216/9f9a86f2-f7ca-45a4-b3ba-8fec10a4fc96)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/153439216/3d6beb34-647d-448a-9837-639ac386ac16)

![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/153439216/baae98cb-c56b-4d8d-be07-7b24a5965d52)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/153439216/a1ada66b-4ea4-4d26-82d3-fb30f0d2936e)

**Comment by realmadrid1809** [comment]
Move the charm effect away from the name. It's covering the name

**Comment by RyuzakiOsu** [comment]
> Move the charm effect away from the name. It's covering the name

is that the fix or do i need to move the charm to send the screenshots again?

**Comment by realmadrid1809** [comment]
That is the fix. Nothing should cover the names while using the counter.
