### ISSUE TITLE
Unable to determine many simplify chinese character. 

### ISSUE THREAD

**Issue by Ginmonsuta** [ssjshields/archetype-counter#49]
Several characters encounter problems when converting from images to text,so far i have  毽 ,茧, 燕,  even after attempting magnifications of 1.0 and 1.25. Changing characters to ones with fewer strokes resolved the issue,but that didn't solve the root problem, is there alternative methods to improve OCR accuracy in the transition from images to text.

![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/159769197/f61a9828-da0a-44cc-866e-22c75dbee4ab)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/159769197/bd15a221-b58c-4702-bce2-25c0eaf6f99c)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/159769197/1fc97fcf-d75c-400b-b96e-3b57822e322f)
![ArchetypeScreenshotSetPixel](https://github.com/ssjshields/archetype-counter/assets/159769197/569653a3-f9b5-4e2c-aa98-eb8a5d090599)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14236886/DEBUG_OCR_OUTPUT.txt)

**Comment by Ginmonsuta** [comment]
add on to the top, 嘴, 雀, these two character unable to scane correctly. 
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14249324/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/159769197/e432f53a-43d7-469b-ad35-914f8ac861c1)

**Comment by AnonymousPoke** [comment]
Issued resolved in v4.0.0.01
