### ISSUE TITLE
臭臭花识别失败

### ISSUE THREAD

**Issue by zsecft2** [ssjshields/archetype-counter#50]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/159863769/beefec26-82ac-40d1-8fc3-aef5c7068bc0)

**Comment by zsecft2** [comment]
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/159863769/8bff4638-b112-4a1a-b2de-c55110030b9a)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/159863769/847b1fa7-899a-419e-8ab0-8c0736c0b894)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/159863769/3dc4e247-e1a4-4cd2-b93c-3bae46ba7d5f)

**Comment by zsecft2** [comment]
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14255341/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
Issued resolved in v4.0.0.1.
