### ISSUE TITLE
小卡比兽识别失败

### ISSUE THREAD

**Issue by zsecft2** [ssjshields/archetype-counter#51]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/159863769/bfb3c633-ad4a-4194-85c7-843201ae0123)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/159863769/fa283f59-4bd2-418c-b6aa-489e676e5c56)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/159863769/fa3ae793-2df1-406d-9b13-1148b04f1a9f)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/159863769/e22f0106-23e1-4dcf-8e97-941418a1fc8c)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14255370/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
Issued resolved in v4.0.0.1. (Better CJK support)
