### ISSUE TITLE
The app goes into the "busy" state only when I minimize/maximize

### ISSUE THREAD

**Issue by F-yol** [ssjshields/archetype-counter#52]
It doesn't seems to work in any way unless I do this. It also counts Slowpokes x2 for some reason!

![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/160557734/8d80a411-6d9e-4aff-a68c-718790e33cc0)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/160557734/57d40793-b8ab-4e31-8c53-a346616880fd)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/160557734/f1057a13-f3ea-49ac-a53f-3a1358d16a4a)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/160557734/76b7e40d-2a9c-4497-9562-5235970e923f)
![ArchetypeScreenshotSetPixel](https://github.com/ssjshields/archetype-counter/assets/160557734/e06d19e8-d3fe-40a5-af24-a187dc8e3ee7)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14338408/DEBUG_OCR_OUTPUT.txt)

**Comment by AnonymousPoke** [comment]
Issue resolved in v4.0.0.1.
