### ISSUE TITLE
Failed scan on Amoonguss

### ISSUE THREAD

**Issue by egarciairizar** [ssjshields/archetype-counter#54]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/134347152/1da9f406-b6ab-4659-b9bc-d56363a63fe9)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/134347152/316b9e92-5e21-4459-9ebc-cdd52b4882a4)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/134347152/6851b9ab-3aab-41a8-82ea-5c52f075dd50)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/134347152/d2f7db9e-c34f-45ae-9199-cbe6292ad42a)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14453725/DEBUG_OCR_OUTPUT.txt)

**Comment by ssjshields** [comment]
@egarciairizar As shown in your third and fourth screenshot, it is not capturing the names properly. What resolution are you using?

**Comment by ssjshields** [comment]
client windowed resolution was too small
