### ISSUE TITLE
Unable to scan Sleeping cascoon 

### ISSUE THREAD

**Issue by wizskr** [ssjshields/archetype-counter#55]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/124992995/015c3822-b03f-4971-824c-62be9466d899)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/124992995/5bb5d45c-ef78-4659-b8c5-d81cbca32754)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/124992995/a958ff13-fcbe-4c1d-9bb2-6974ec87d9b1)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/124992995/1abe585e-bfba-4f63-ba45-02d223ccb23b)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14484039/DEBUG_OCR_OUTPUT.txt)

**Comment by realmadrid1809** [comment]
Looks like you reduced the battle window size in the pokemmo settings. We will fix this in an upcoming update. In the meantime change the size back to 100

**Comment by AnonymousPoke** [comment]
Issue resolved in v4.0.0.1
