### ISSUE TITLE
The program can't see PokéMMO, infinite alert 

### ISSUE THREAD

**Issue by F-yol** [ssjshields/archetype-counter#56]
When I open the program and turn it on, it gives me this message:
![image](https://github.com/ssjshields/archetype-counter/assets/160557734/e44fef03-bb0b-49ee-b1c3-5fc9ce8e0f0b)

Then, if I have PokéMMO open, it gets closed, and I get this message:
![image](https://github.com/ssjshields/archetype-counter/assets/160557734/9df34936-dc42-4b75-ba9e-d27ac1f6e601)

No matter how many times I click yes, the message reappears every time and nothing else happens. I can try to open the game myself, but then the counter won't work. What can I do?

**Comment by F-yol** [comment]
Here:
![image](https://github.com/ssjshields/archetype-counter/assets/160557734/78fe7b8b-7fee-4ceb-bfac-e1867bfc525c)

**Comment by ssjshields** [comment]
more than likely resolved in v4, v3 will no longer be supported.

currenting in the "testing" branch.
