### ISSUE TITLE
Unable to scan Nidoran Female

### ISSUE THREAD

**Issue by LeBoto** [ssjshields/archetype-counter#57]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/46331272/9520fdbc-55fb-44f6-a205-2fc53abe7e9b)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/46331272/15e5307d-a418-483e-b247-9061e3044967)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/46331272/1a377649-f37e-493e-a683-235f8fe4f3ae)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/46331272/5f73f9de-7a56-4267-b6c6-8667449e0b75)
[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/14628324/DEBUG_OCR_OUTPUT.txt)

**Comment by nicwisely** [comment]
I get an error when Nidoran female shows up as well.

**Comment by ssjshields** [comment]
resolved in v4, v3 will no longer be supported.

currenting in the "testing" branch.
