### ISSUE TITLE
Don't recognize Gloom (sleeping)

### ISSUE THREAD

**Issue by shyyks** [ssjshields/archetype-counter#60]
The counter don't recognise gloom and the error window pops up. I play with 10 on battle sceen and so I tried to upscale to 100 but still pop up  the error, I play on a vetical monitor maybe thats the issue.

I hope these files can help.
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/172159355/6ca04afa-bdd7-426e-9871-44bc3e712875)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/172159355/d872dd48-0a9f-47ad-825f-d208e218968e)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/172159355/754fb594-febc-4f86-b13b-8b8806cbd512)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/172159355/ac04c3ce-7b4f-491a-b702-a5f382eb5c15)
[DEBUG_OCR_OUTPUT.txt](https://github.com/user-attachments/files/15750352/DEBUG_OCR_OUTPUT.txt)

**Comment by ssjshields** [comment]
resolved in v4, v3 will no longer be supported.

currenting in the "testing" branch.
