### ISSUE TITLE
Failing to scan - Italian rom

### ISSUE THREAD

**Issue by shyyks** [ssjshields/archetype-counter#63]
The counter seem recognising that i'm in battle but is not registering the pokemon encountered. I thougth it was begcause i play in split screen on my monitor but when i tried fullscreen and battle window size 100 still don't work. Maybe this datas can help in the future :)
![AC_Debug_Screenshot](https://github.com/ssjshields/archetype-counter/assets/172159355/0bb5417f-ad71-4b74-af88-2480a8a666b4)
[AC_Debug_Output.txt](https://github.com/user-attachments/files/16043453/AC_Debug_Output.txt)

**Comment by ssjshields** [comment]
you can't use full-screen PokeMMO I believe, use borderless mode. let us know if that resolves your issue. 
i'll have to add that back to the documentation

**Comment by shyyks** [comment]
oh yeah I express myself wrongly, i simply extended my window to full screen. Now that you mentioned it i also tried in borderless fullscreen but still no response. Maybe the fact that i don't have an english rom interfere with the counter? Do you maybe suggeto to reinstall all the package?
Thx for the response and help, really appreciate:)
Below the files from my test in borderless fullscreen, maybe can help.
![AC_Debug_Screenshot](https://github.com/ssjshields/archetype-counter/assets/172159355/fdc41d97-ed33-4759-90e5-4e25fcf81b5a)
[AC_Debug_Output.txt](https://github.com/user-attachments/files/16044078/AC_Debug_Output.txt)

**Comment by ssjshields** [comment]
@shyyks you're using Spanish ROM correct?

**Comment by shyyks** [comment]
@ssjshields no i'm using an italian rom, pokemon names are the same as english

**Comment by ssjshields** [comment]
@shyyks this should be resolved now. Please try the latest version.
