### ISSUE TITLE
Lure double enocunters are incorrectly counted

### ISSUE THREAD

**Issue by Feqgbeko** [ssjshields/archetype-counter#68]
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/8512636/a0634d34-813c-455a-ae86-08b0d56670de)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/8512636/481f7d85-9e42-4c6c-95bb-1ca43474576d)
![ArchetypeScreenshotEncounterEx](https://github.com/ssjshields/archetype-counter/assets/8512636/07f99ef4-d0fb-4489-ae67-bdcafd5030a4)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/8512636/ad350126-a43e-4fad-b2b6-7f9fe442deee)
[DEBUG_OCR_OUTPUT.txt](https://github.com/user-attachments/files/16142224/DEBUG_OCR_OUTPUT.txt)
i noticed while using lures you can sometimes encounter 2 different pokemon at once. the counter just counts them both as the first pokemon even if they are 2 different species. luckily it's not something major or app breaking, but i still thought it was worth mentioning it here

**Comment by ssjshields** [comment]
@Feqgbeko this is resolved in the latest version 4+. Please refer to the Wiki for usage information.
