### ISSUE TITLE
error appear "unable to scan" to a every single pokemon 

### ISSUE THREAD

**Issue by luist2810** [ssjshields/archetype-counter#81]
in searching for a shiny and it appears "unable for scan" with every single pokemon who appears idk how to solve it

**Comment by ssjshields** [comment]
https://github.com/ssjshields/archetype-counter/wiki/Frequently-Asked-Questions#how-can-i-report-a-bug

**Comment by AnonymousPoke** [comment]
@luist2810 If this is still an issue beyond what @ssjshields has provided, then please respond with the correct information or we will be closing this issue down.

**Comment by ssjshields** [comment]
not enough info
