### ISSUE TITLE
Route 3 issue

### ISSUE THREAD

**Issue by pedroalayon** [ssjshields/archetype-counter#82]
Hey, i've got this issue for the past months in the same route, when a spearow or a nidoran appears the counter doesn't work properly, it just says that it failed to scan, what should i do?

![ArchetypeScreenshot](https://github.com/user-attachments/assets/58965440-4d5d-4606-8195-72c239e07bef)
![ArchetypeScreenshotEncounter](https://github.com/user-attachments/assets/05a2fdd6-481a-4090-a1db-cef52e02e3dc)
![ArchetypeScreenshotEncounterEx](https://github.com/user-attachments/assets/3d1be844-c36e-41ce-8cfd-32c634580fd7)
![ArchetypeScreenshotMagick](https://github.com/user-attachments/assets/2f575974-d24c-4fb1-9f10-80982021beb2)
[DEBUG_OCR_OUTPUT.txt](https://github.com/user-attachments/files/17348213/DEBUG_OCR_OUTPUT.txt)

**Comment by pedroalayon** [comment]
![ArchetypeScreenshotEncounter](https://github.com/user-attachments/assets/64217be2-d4d4-4978-b5bf-aa961549d8ec)
![ArchetypeScreenshotEncounterEx](https://github.com/user-attachments/assets/56519872-4bf2-49d2-ab02-b209019a28c4)
![ArchetypeScreenshotMagick](https://github.com/user-attachments/assets/54c4ac17-f415-4190-a938-6943f012b882)
[DEBUG_OCR_OUTPUT.txt](https://github.com/user-attachments/files/17348246/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/user-attachments/assets/66205dc2-5f24-400f-b612-8cf9a197785c)

**Comment by ssjshields** [comment]
@pedroalayon sorry for late reply.

the problem with both of these issues is results may be inconsistent depending on battle background or even time of day in-game.

For nidoran: the gender symbol bugs the result out. you can either edit the string and remove it entirely (this would prevent the error all together, I would do it for female variant too) or add the After Cleanup result to the name fix file.

For Spearow: its the sleep icon. same as above, you can try to add the After Cleanup result to the name fix file. this can possibly be circumvented by using the archetype custom icons https://github.com/ssjshields/archetype/releases/tag/beta-icons
